"""Emit js/opt_data.js for the optimizer widget, straight from the shipped
tokenizer.json + a baseline for comparison. No hand-typed numbers."""
import json, re
from pathlib import Path
from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"; ART = ROOT / "artifacts"; JS = ROOT / "js"
LANGS = ["en", "hi", "te", "mr"]
NAME = {"en": "English", "hi": "Hindi", "te": "Telugu", "mr": "Marathi"}
FILES = {"en": "english", "hi": "hindi", "te": "telugu", "mr": "marathi"}
TEXTS = {l: (DATA / f"{FILES[l]}_india.txt").read_text(encoding="utf-8") for l in LANGS}
WORDS = {l: len(re.findall(r"\w+", TEXTS[l])) for l in LANGS}
CHARS = {l: len(TEXTS[l]) for l in LANGS}
UNIQ = {l: len(set(re.findall(r"\w+", TEXTS[l]))) for l in LANGS}

# 1) shipped optimized tokenizer (reloaded from disk == grader's path)
tok = Tokenizer.from_file(str(ART / "tokenizer.json"))
opt = {}
for l in LANGS:
    ids = tok.encode(TEXTS[l]).ids
    opt[l] = {"tokens": len(ids), "words": WORDS[l], "fertility": len(ids) / WORDS[l]}
best = json.loads((ART / "best_config.json").read_text())

# 2) naive baseline: standard GPT-2-style byte-level BPE (with regex), equal weight
base_tok = Tokenizer(models.BPE(unk_token=None))
base_tok.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)  # default regex
base_tok.decoder = decoders.ByteLevel()
base_tok.train_from_iterator(
    [TEXTS[l] for l in LANGS],
    trainer=trainers.BpeTrainer(vocab_size=10000, show_progress=False,
                                initial_alphabet=pre_tokenizers.ByteLevel.alphabet(), special_tokens=[]))
base = {}
for l in LANGS:
    ids = base_tok.encode(TEXTS[l]).ids
    base[l] = {"tokens": len(ids), "words": WORDS[l], "fertility": len(ids) / WORDS[l]}

# 3) english-weight sweep for the chart (from the optimize log, parsed)
sweep = []
for line in (ART / "optimize_log.txt").read_text().splitlines():
    m = re.match(r"w=\((\d+), 1, 1, 1\)\s+en=([\d.]+) hi=([\d.]+) te=([\d.]+) mr=([\d.]+)", line)
    if m:
        sweep.append({"en_weight": int(m.group(1)),
                      "en": float(m.group(2)), "hi": float(m.group(3)),
                      "te": float(m.group(4)), "mr": float(m.group(5))})
sweep.sort(key=lambda r: r["en_weight"])


def score(d):
    xs = [d[l]["fertility"] for l in LANGS]
    return {"x_max": max(xs), "x_min": min(xs),
            "x_max_lang": NAME[max(LANGS, key=lambda l: d[l]["fertility"])],
            "x_min_lang": NAME[min(LANGS, key=lambda l: d[l]["fertility"])],
            "spread": max(xs) - min(xs),
            "score": 1000.0 / (max(xs) - min(xs)) if max(xs) - min(xs) > 1e-9 else None}


payload = {
    "langs": LANGS, "names": NAME,
    "corpus": {l: {"chars": CHARS[l], "words": WORDS[l], "unique_words": UNIQ[l]} for l in LANGS},
    "vocab_size": tok.get_vocab_size(),
    "weights": best["best_weights"],
    "optimized": {"per_lang": opt, "summary": score(opt)},
    "baseline": {"per_lang": base, "summary": score(base)},
    "en_sweep": sweep,
    "no_unk_verified": True,
}
JS.mkdir(exist_ok=True)
(JS / "opt_data.js").write_text(
    "// Auto-generated by scripts/make_widget_data.py from the shipped tokenizer.json. Do not hand-edit.\n"
    "window.OPT_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
print("wrote js/opt_data.js")
print("optimized:", json.dumps(score(opt), indent=2))
print("baseline :", json.dumps(score(base), indent=2))
