// Auto-generated by scripts/make_widget_data.py from the shipped tokenizer.json. Do not hand-edit.
window.OPT_DATA = {
  "langs": [
    "en",
    "hi",
    "te",
    "mr"
  ],
  "names": {
    "en": "English",
    "hi": "Hindi",
    "te": "Telugu",
    "mr": "Marathi"
  },
  "corpus": {
    "en": {
      "chars": 196491,
      "words": 31641,
      "unique_words": 7286
    },
    "hi": {
      "chars": 71883,
      "words": 23002,
      "unique_words": 1916
    },
    "te": {
      "chars": 31858,
      "words": 10490,
      "unique_words": 1090
    },
    "mr": {
      "chars": 38925,
      "words": 14207,
      "unique_words": 1173
    }
  },
  "vocab_size": 10000,
  "weights": {
    "en": 7,
    "hi": 1,
    "te": 2,
    "mr": 1
  },
  "optimized": {
    "per_lang": {
      "en": {
        "tokens": 37313,
        "words": 31641,
        "fertility": 1.1792610853007175
      },
      "hi": {
        "tokens": 27133,
        "words": 23002,
        "fertility": 1.1795930788627076
      },
      "te": {
        "tokens": 12603,
        "words": 10490,
        "fertility": 1.2014299332697806
      },
      "mr": {
        "tokens": 16934,
        "words": 14207,
        "fertility": 1.1919476314492856
      }
    },
    "summary": {
      "x_max": 1.2014299332697806,
      "x_min": 1.1792610853007175,
      "x_max_lang": "Telugu",
      "x_min_lang": "English",
      "spread": 0.022168847969063155,
      "score": 45108.34308555455
    }
  },
  "baseline": {
    "per_lang": {
      "en": {
        "tokens": 49442,
        "words": 31641,
        "fertility": 1.5625928384058658
      },
      "hi": {
        "tokens": 42142,
        "words": 23002,
        "fertility": 1.8321015563864012
      },
      "te": {
        "tokens": 20627,
        "words": 10490,
        "fertility": 1.9663489037178266
      },
      "mr": {
        "tokens": 26862,
        "words": 14207,
        "fertility": 1.8907580770042938
      }
    },
    "summary": {
      "x_max": 1.9663489037178266,
      "x_min": 1.5625928384058658,
      "x_max_lang": "Telugu",
      "x_min_lang": "English",
      "spread": 0.40375606531196073,
      "score": 2476.7429790246083
    }
  },
  "en_sweep": [
    {
      "en_weight": 1,
      "en": 1.434,
      "hi": 0.813,
      "te": 1.011,
      "mr": 0.823
    },
    {
      "en_weight": 2,
      "en": 1.325,
      "hi": 0.902,
      "te": 1.114,
      "mr": 0.917
    },
    {
      "en_weight": 3,
      "en": 1.277,
      "hi": 0.985,
      "te": 1.202,
      "mr": 0.998
    },
    {
      "en_weight": 4,
      "en": 1.248,
      "hi": 1.052,
      "te": 1.285,
      "mr": 1.059
    },
    {
      "en_weight": 5,
      "en": 1.228,
      "hi": 1.107,
      "te": 1.359,
      "mr": 1.109
    },
    {
      "en_weight": 6,
      "en": 1.216,
      "hi": 1.157,
      "te": 1.401,
      "mr": 1.17
    },
    {
      "en_weight": 7,
      "en": 1.207,
      "hi": 1.196,
      "te": 1.452,
      "mr": 1.206
    },
    {
      "en_weight": 8,
      "en": 1.201,
      "hi": 1.228,
      "te": 1.484,
      "mr": 1.24
    },
    {
      "en_weight": 10,
      "en": 1.189,
      "hi": 1.293,
      "te": 1.58,
      "mr": 1.296
    },
    {
      "en_weight": 12,
      "en": 1.182,
      "hi": 1.336,
      "te": 1.629,
      "mr": 1.347
    }
  ],
  "no_unk_verified": true
};
